server:
  port: 8084

spring:
  application:
    name: cola-tools
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml


#dubbo:
#  protocol:
#    name: dubbo
#    host: 127.0.0.1
#    port: 20881
#  application:
#    qos-port: 33334
